/*
* this is a first set of potential data
*
*/

var herbs = [["Url http://www.kaesekessel.de/kraeuter/", "geschützt", "Name", "Jan", "Feb", "März", "Apr", "Mai", "Jun", "Jul", "Aug", "Sept", "Okt", "Nov", "Dez", "Gefahr", "Anwendung", "Gebiete"],
["a/ackergauchheil.htm", "", "Ackergauchheil", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "X", "", "Lehmboden, Acker- und Gartenland"],
["a/ackerschachtelhalm.htm", "", "Ackerschachtelhalm", "", "", "", "", "Triebe", "Triebe", "", "", "", "", "", "", "", "", ""],
["z/zaunwinde.htm", "", "Ackerwinde", "", "", "Wurzel", "Wurzel", "", "Kraut", "Kraut", "Kraut", "Wurzel", "Wurzel", "", "", "X", "", "Äcker, Gärten, Ödland, Wege. Besonders auf basen- und stickstoffsalzreichen, humusarmen Lehm- oder Tonboden"],
["a/ackerwitwenblume.htm", "", "Acker-Witwenblume", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["a/alant.htm", "", "Alant", "", "", "", "", "", "", "", "", "Wurzel", "Wurzel", "", "", "nein", "", "Feuchten Standorte, besonders in Hecken, Ufergebüschen, Parkanlagen und Wiesengräben sowie an Waldwegen und -rändern"],
["a/ampfer.htm", "", "Ampfer, Sauerampfer", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", "", "", ""],
["a/ampfer.htm", "", "Ampfer, Krauser", "", "", "", "", "", "", "", "", "", "Wurzel", "Wurzel", "", "XX", "Homöo, Rumex", "Nähe Brennessel, Wiesen, Grasplätze, Schutt, Sumpfwiesen, sehr gerne lehmig-tonige Böden und verdichteter Untergrund mit Staunässe"],
["a/ampfer.htm", "", "Ampfer, Römischer", "", "", "", "", "Blatt", "", "", "", "", "", "", "", "", "", ""],
["a/andorn.htm", "*NS", "Andorn", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["a/anis.htm", "", "Anis", "", "", "", "", "", "", "Früchte", "Früchte", "Früchte", "", "", "", "", "", ""],
["a/apfel.htm", "", "Apfel", "", "", "", "", "", "", "Früchte", "Früchte", "Früchte", "Früchte", "Früchte", "Früchte", "", "", ""],
["a/arnika.htm", "*NS", "Arnika", "", "", "", "Wurzel", "", "", "Blüte", "Blüte", "", "Wurzel", "", "", "O", "", "Sammelverbot, humusreichen bis sandigen, ungedüngten Böden von der Ebene bis in die hochalpine Stufe (bis über 2000m). Sie ist kalkscheu. Sie wächst auf Matten, Wiesen, Heiden, ausgetrockneten Hochmooren und in lichten Nadelwäldern. Sie lebt außerdem auf torfigen Böden"],
["a/augentrost.htm", "", "Augentrost", "", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "nein", "", "mageren Wiesen und Heiden, in Mooren und lichten Wäldern von der Ebene bis in die Alpen. Düngung schadet dem Augentrost."],
["b/baldrian.htm", "", "Baldrian", "", "", "", "", "", "", "", "", "Wurzel", "Wurzel", "", "", "X", "Beruhigend", "Feuchte Standorte"],
["b/barlauch.htm", "", "Bärlauch", "", "", "", "Zwiebel Blatt", "Zwiebel Blatt", "", "", "", "", "", "", "", "", "", ""],
["b/baerlapp.htm", "*NS", "Bärlapp", "", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", ""],
["b/beifuss.htm", "", "Beifuss", "", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["b/beinwell.htm", "", "Beinwell", "", "", "Wurzel", "Wurzel", "Blatt", "Blatt", "Blatt", "", "Wurzel", "Wurzel", "", "", "O", "Verstauchung, Prellung", "feuchten Boden und ist daher besonders häufig an Wasserläufen oder in Senken zu finden"],
["b/benedikt.htm", "", "Benediktenkraut", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", ""],
["b/besenginster.htm", "", "Besenginster", "", "", "", "", "Triebe", "", "", "", "", "", "", "", "", "", ""],
["b/bibernelle.htm", "", "Bibernelle", "", "", "Wurzel", "Wurzel", "", "", "", "", "Wurzel", "Wurzel", "", "", "nein", "schleimlösend", "an Zäunen, Wegen und auf Wiesen"],
["b/birke.htm", "", "Birke", "", "", "", "", "Blatt", "Blatt", "", "", "", "", "", "", "", "", ""],
["b/blutwurz.htm", "", "Blutwurz", "", "", "Wurzel", "Wurzel", "", "", "", "", "Wurzel", "Wurzel", "", "", "O", "Mund, Rachen, Gastro", "verbreitete Pflanze wächst vom Tiefland bis bis über 2000m."],
["b/bockshornklee.htm", "", "Bockshornklee", "", "", "", "", "", "Samen", "Samen", "Samen", "", "", "", "", "", "", ""],
["b/breitw.htm", "", "Breitwegerich", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["b/brennessel.htm", "", "Brennessel", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", "", ""],
["b/brombeere.htm", "", "Brombeere", "", "", "", "", "Blatt Triebe", "Blatt Triebe", "Früchte", "Früchte", "Früchte", "Früchte", "Früchte", "", "nein", "Nervosität, Blutbildend", "Wäldern, Gebüschen und Hecken, Industriebrachland, an Wegen, auf Kahlschlägen und in verwilderten Gärten"],
["d/dill.htm", "", "Dill", "", "", "", "", "", "Blatt", "Blatt", "Samen", "Samen", "", "", "", "", "", ""],
["e/eberesche.htm", "", "Eberesche", "", "", "", "", "", "", "", "Früchte", "Früchte", "Früchte", "Früchte", "", "O (Vergiftung mit med. Kohle behandeln)", "Stoffwechsel, Kreislauf", "im Gebirge bis zur Baumgrenze im Mischwald und auf Feld und Flur, vollsonnig bis halbschattig, hitzeempfindlich, Temperatur: warm bis kühl, frosthart, Bodenfeuchte: trocken bis naß, salzempfindlich"],
["t/thymian.htm", "", "Echter Thymian", "", "", "", "", "", "Kraut", "Kraut", "", "Kraut", "", "", "", "", "", ""],
["e/ehrenpreis.htm", "", "Ehrenpreis", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["e/ehrenpreis_gamander.htm", "", "Ehrenpreis, Gamander", "", "", "", "Blüte", "", "", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["e/eibisch.htm", "", "Eibisch", "", "", "", "", "Blatt", "Blatt", "", "", "", "Wurzel", "Wurzel", "", "O", "Reizung, Rachen", "ursprüngliche Wuchsform auf salz- und kalihaltigen Böden, stellenweise auf feuchten Wiesen, im Ufergebüsch und auf Viehweiden"],
["e/eiche.htm", "", "Eiche", "", "", "Rinde", "Rinde", "", "Blatt", "Blatt", "", "", "Früchte", "", "", "O, Gegenmittel bei Vergiftung durch Pilze, Nachtschatten, Herstzeitlose, ...", "Hautstärkend, Zahnfleisch stärkend", "Stieleiche beforzugt feuchte, oft magere Böden, Laub- und Nadelwälder. Die Traubeneiche bevorzugt magere Böden. Sie steht gern alleine zwischen anderen Bäumen"],
["e/engelwurz.htm", "", "Engelwurz", "", "", "Wurzel", "", "", "", "", "", "", "Wurzel", "", "", "O", "Verdauung, Blähung", "Gräben und Flußufern, auf feuchten Wiesen und Flachmooren, in Gebüschen und Erlenwäldern"],
["e/erdbeere.htm", "", "Erdbeere", "", "", "Wurzel", "Wurzel", "Wurzel Blatt", "BlattFrüchte", "Früchte", "", "", "Wurzel", "Wurzel", "", "nein", "keine", "bis zur Waldgrenze. Lichte Stellen auf nährstoffreichen Böden von Wäldern, Hecken, Waldränder, Waldwege, Holzschläge"],
["e/erdrauch.htm", "", "Erdrauch", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["f/faulbaum.htm", "", "Faulbaum", "", "", "", "Rinde", "Rinde", "Rinde", "", "", "", "", "", "", "", "", ""],
["t/thymian.htm", "", "Feldthymian", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["f/fenchel.htm", "", "Fenchel", "", "", "", "", "", "", "", "Früchte", "Früchte", "", "", "", "", "", ""],
["f/frauenmantel.htm", "", "Frauenmantel", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["e/ehrenpreis_gamander.htm", "", "Gamander - Ehrenpreis", "", "", "", "Blüte", "", "", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["g/gaensebluemchen.htm", "", "Gänseblümchen", "", "", "Blüte", "Blüte", "Blüte", "Blüte", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["g/gaensefingerkraut.htm", "", "Gänsefingerkraut", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["g/giersch.htm", "", "Giersch", "", "", "Wurzel", "Wurzel", "Blatt Triebe", "Blatt Triebe", "Früchte Blatt Triebe", "Früchte", "", "Wurzel", "Wurzel", "", "O / nein", "Entzündungshemmend, Insektenstiche, harntreibend", "schattigen, stickstoffreichen Standorten in Gärten, Wäldern, Hecken und Gebüschen."],
["g/glatthafer.htm", "", "Glatthafer", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["g/goldrute.htm", "", "Goldrute", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["g/gundermann.htm", "", "Gundermann", "", "", "", "Blatt Kraut", "Blatt Kraut", "Blatt Kraut", "", "", "", "", "", "", "", "", ""],
["g/guensel.htm", "", "Günsel", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", "", ""],
["h/habichtskraut.htm", "", "Habichtskraut", "", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", ""],
["h/hafer.htm", "", "Hafer", "", "", "", "", "", "", "", "Früchte", "Früchte", "", "", "", "", "", ""],
["h/hahnenfuss.htm", "", "Hahnenfuß", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["h/hasel.htm", "", "Hasel", "", "", "", "", "", "", "", "", "Früchte", "Früchte", "", "", "", "", ""],
["h/hauhechel.htm", "", "Hauhechel", "", "", "", "", "", "", "", "Wurzel", "Wurzel", "Wurzel", "", "", "nein", "Blase, Niere, Harntreibend, nicht nierenreizend", "Kalkhaltige Magerstandorte, Extensivweiden, Wegränder, Trockenrasen. Da das Vieh Hauhechel meidet, breitet es sich besonders auf Weiden leicht aus"],
["h/hauswurz.htm", "*NS", "Hauswurz", "", "", "", "", "Blatt", "Blatt", "Blatt", "Blatt", "Blatt", "", "", "", "", "", ""],
["h/heidelbeere.htm", "", "Heidelbeere", "", "", "", "", "", "BlattFrüchte", "BlattFrüchte", "BlattFrüchte", "", "", "", "", "", "", ""],
["h/herzgespann.htm", "*NS", "Herzgespann", "", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["h/himbeere.htm", "", "Himbeere", "", "", "", "", "Blatt", "Früchte", "Früchte", "Früchte", "Früchte", "", "", "", "", "", ""],
["h/hirtentaeschel.htm", "", "Hirtentäschel", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["h/hohlzahn.htm", "", "Hohlzahn", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["h/holunder.htm", "", "Holunder", "", "", "", "", "", "Blatt", "Blatt", "", "Früchte", "Früchte", "", "", "nein (nicht roh)", "Fieber, Husten, Immunstärkend", "feuchten Waldblößen, an steinigen, buschigen Stellen und an Flüssen, in Schluchten und an Hohlwegen"],
["h/hopfen.htm", "", "Hopfen", "", "", "", "", "", "", "Blatt", "Blatt", "Früchte", "Früchte", "", "", "O", "beruhigend, antibakteriell", "feuchten Standorten. Man findet ihn an Hecken und Zäunen, Waldrändern und in Auenwäldern"],
["h/huflattich.htm", "", "Huflattich", "", "", "Blüte", "Blüte", "Blatt", "Blatt", "", "", "", "", "", "", "", "", ""],
["h/hundsrose.htm", "", "Hunds- und Heckenrose", "", "", "", "", "", "Blüte", "", "", "Früchte", "Früchte", "Früchte", "", "nein", "Vitaminstabil, abführend", "Weg- und Feldrändern zu finden. Magere Weiden, lichte Buschwälder, Waldränder. Selten über 1300m"],
["j/johannisk.htm", "", "Johanniskraut", "", "", "", "", "", "", "Blüte Kraut", "Blüte Kraut", "", "", "", "", "", "", ""],
["k/kalmus.htm", "", "Kalmus", "", "", "Wurzel", "", "", "", "", "", "", "Wurzel", "Wurzel", "", "O / X", "Erschöpfung, Verdauung, Blähung", "Uferregionen stehender und fließender Gewässer oder sumpfige, nicht trocknende Stellen"],
["k/kamille.htm", "", "Kamille", "", "", "", "", "Blüte", "Blüte", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["k/kapuzinerkresse.htm", "", "Kapuzinerkresse", "", "", "", "", "Blüte Blatt", "Blüte Blatt", "Blüte Blatt", "Blüte Blatt", "Blüte Blatt Samen", "Blüte Blatt Samen", "", "", "O", "Alkoholverstärkend", "Balkon, Garten"],
["k/klatschmohn.htm", "", "Klatschmohn", "", "", "", "", "Blüte", "Blüte", "", "", "", "", "", "", "", "", ""],
["k/klettenlab.htm", "", "Klettenlabkraut", "Triebe", "Triebe", "Triebe", "Triebe", "Triebe", "Triebe", "Kraut", "Triebe", "Triebe", "Triebe", "Triebe", "Triebe", "nein", "innerlich reinigend, Lymphen", "Feuchte, nährstoffreiche und stickstoffhaltige Lehmböden, sächst auf Äckern, in Gärten, Schuttplätzen und in Gebüschen."],
["k/knoblauch.htm", "", "Knoblauch", "", "", "", "", "", "", "Zwiebel", "", "Zwiebel", "Zwiebel", "", "", "", "", ""],
["k/kohl.htm", "", "Kohl", "", "", "", "", "", "", "", "", "", "Kohl", "", "", "", "", ""],
["k/koenigsk.htm", "", "Königskerze", "", "", "", "", "", "", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["l/lavendel.htm", "", "Lavendel", "", "", "", "", "", "", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["l/liebstock.htm", "", "Liebstock", "", "", "", "", "", "Kraut", "Kraut", "Früchte", "Früchte", "Wurzel", "", "", "", "", ""],
["l/linde.htm", "", "Linde", "", "", "", "", "", "Blüte", "Blüte", "", "", "", "", "", "", "", ""],
["l/loewenzahn.htm", "", "Löwenzahn", "", "", "", "Blüte Blatt Wurzel", "Blüte Blatt Wurzel", "", "", "", "", "", "", "", "", "", ""],
["l/lungenkraut.htm", "", "Lungenkraut", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", "", ""],
["m/maedesuess.htm", "", "Mädesüß", "", "", "", "", "Blüte", "Blüte", "Blüte", "", "", "", "", "", "", "", ""],
["m/majoran.htm", "", "Majoran", "", "", "", "", "", "", "Kraut Blatt", "Kraut Blatt", "Kraut Blatt", "", "", "", "", "", ""],
["m/mariendistel.htm", "*NS", "Mariendistel", "", "", "", "", "", "", "Blüte", "Blüte Samen", "Samen", "Samen", "", "", "", "", ""],
["m/veilchen.htm", "", "Märzveilchen", "", "", "Kraut Wurzel", "Kraut Wurzel", "", "", "", "", "Wurzel", "Wurzel", "", "", "", "", ""],
["m/melde.htm", "", "Melde", "", "", "", "", "", "", "Kraut", "", "", "", "", "", "", "", ""],
["m/melisse.htm", "", "Melisse", "", "", "", "", "", "Blatt", "Blatt", "Blatt", "", "", "", "", "", "", ""],
["m/mistel.htm", "", "Mistel (Laub)", "", "", "Kraut", "Kraut", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "XX", "Krebsvermeidend, Bauchspeicheldrüse, Hormone", "schmarotzt auf verschiedenen Hölzern und ist von der Ebene bis in Mittelgebirgshöhen anzutreffen"],
["m/mistel.htm", "", "Mistel (Nadel)", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", "", "", "", ""],
["m/moenchspfeffer.htm", "", "Mönchspfeffer", "", "", "", "", "", "", "", "", "", "Früchte", "", "", "", "", "Mittelmeergebiet, heute verbreitet in allen milden Gebieten"],
["m/mutterkraut.htm", "", "Mutterkraut", "", "", "", "", "Blüte Blatt", "Blüte Blatt", "Blüte Blatt", "Blüte Blatt", "Blüte Blatt", "", "", "", "", "", ""],
["n/nachtkerze.htm", "", "Nachtkerze", "", "", "", "", "", "Blatt", "Samen Blatt", "Samen Blatt", "Samen Blatt", "Wurzel", "", "", "", "", ""],
["n/nelkenwurz.htm", "", "Nelkenwurz", "", "", "Wurzel", "Wurzel", "Blatt Kraut", "Blatt Kraut", "Blatt Kraut", "Blatt Kraut", "Wurzel", "Wurzel", "", "", "", "", ""],
["n/nussbaum.htm", "", "Nußbaum", "", "", "", "", "", "Blatt", "", "Früchte", "Früchte", "", "", "", "", "", ""],
["o/ochsenzunge.htm", "", "Ochsenzunge", "", "", "", "", "Kraut Blüte", "Kraut Blüte", "Blüte", "Blüte", "Blüte", "Wurzel", "", "", "", "", ""],
["o/odermennig.htm", "", "Odermennig", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["o/oregano.htm", "", "Oregano", "", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["p/pastinake.htm", "", "Pastinake", "", "", "", "", "", "", "", "Wurzel", "Wurzel", "Wurzel", "Wurzel", "Wurzel", "O / nein", "Schlaflosigkeit, Nahrungszusatz", "Wegränder, Schuttplätze, Im Norden weniger, im Süden mehr"],
["p/pestwurz.htm", "", "Pestwurz", "", "", "Wurzel", "Wurzel", "Wurzel Blatt", "", "", "", "", "", "", "", "", "", ""],
["p/petersilie.htm", "", "Petersilie", "Blatt", "Blatt", "Wurzel Blatt", "Wurzel Blatt", "Blatt", "Blatt", "Blatt", "Früchte Blatt", "Früchte Blatt", "Blatt", "Blatt", "Blatt", "O / X", "Milben, Läuse, Harntreibend", "Küchengärten, Felder, aber auch verwildert."],
["p/pfefferminze.htm", "", "Pfefferminze", "", "", "", "", "", "Blatt", "Blatt", "", "", "", "", "", "", "", ""],
["p/pfennigkraut.htm", "", "Pfennigkraut", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", ""],
["q/quecke.htm", "", "Quecke", "", "", "Wurzel", "Wurzel", "", "", "", "", "Wurzel", "Wurzel", "", "", "", "", ""],
["r/rainfarn.htm", "", "Rainfarn", "", "", "", "", "", "", "Kraut Blüte", "Kraut Blüte", "Kraut", "Kraut", "", "", "", "", ""],
["r/ringelblume.htm", "", "Ringelblume", "", "", "", "", "", "Blüte", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["r/rittersporn.htm", "", "Rittersporn", "", "", "", "", "Blüte", "Blüte", "Blüte", "Blüte", "", "", "", "", "", "", ""],
["r/rosmarin.htm", "", "Rosmarin", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", "", ""],
["s/salbei.htm", "", "Salbei", "", "", "", "", "Blatt", "Blatt", "Blatt", "Blatt", "Blatt", "", "", "", "", "", ""],
["s/schafgarbe.htm", "", "Schafgarbe", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["s/scharbockskraut.htm", "", "Scharbockskraut", "", "", "Blatt Blüte", "Blatt Blüte", "", "", "", "", "", "", "", "", "", "", ""],
["s/schlehe.htm", "", "Schlehe", "", "", "Blüte", "Blüte", "", "", "", "", "", "", "Früchte", "Früchte", "O / nein", "abführen, entzündungshemmend, harntreibend", "Sonnige Hügel, trockene, lichte Laubwälder. Sammeln Früchte: Nach dem ersten Frost"],
["s/schluesselblume.htm", "*NS", "Schlüsselblume", "", "", "Blatt", "Blatt", "Blatt", "", "", "", "", "Wurzel", "", "", "", "", ""],
["s/schoellkraut.htm", "", "Schöllkraut", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", "", "", ""],
["s/schwarzkuemmel.htm", "", "Schwarzkümmel", "", "", "", "", "", "", "", "", "Samen", "", "", "", "", "", ""],
["s/sellerie.htm", "", "Sellerie", "", "", "", "", "Kraut", "Kraut", "Kraut Wurzel Samen", "Kraut Wurzel Samen", "Kraut Wurzel Samen", "Wurzel", "", "", "", "", ""],
["s/senf.htm", "", "Senf", "", "", "", "", "", "", "Samen", "Samen", "Samen .", "", "", "", "", "", ""],
["s/sonnenhut.htm", "", "Sonnenhut", "", "", "Wurzel", "Wurzel", "Kraut Wurzel", "Kraut", "Kraut", "Kraut", "Wurzel", "Wurzel", "", "", "", "", ""],
["s/spargel.htm", "", "Spargel", "", "", "", "Triebe", "Triebe", "Triebe", "", "", "", "", "", "", "", "", ""],
["b/breitw.htm", "", "Spitzwegerich", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["s/wildes_stiefmuetterchen.htm", "", "Stiefmütterchen, wildes", "", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", "", ""],
["s/suessholz.htm", "", "Süßholz", "", "", "", "", "", "", "", "", "", "Wurzel", "", "", "", "", ""],
["t/weisse-taubnessel.htm", "", "Taubnessel (weiss und gelb)", "", "", "", "", "Blüte", "Blüte", "Blüte", "", "", "", "", "", "", "", ""],
["t/tausendguldenkraut.htm", "", "Tausendguldenkraut", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["t/thymian.htm", "", "Thymian", "", "", "", "", "", "Kraut", "Kraut", "", "Kraut", "", "", "", "", "", ""],
["v/vogelknoeterich.htm", "", "Vogelknöterich", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["w/wacholder.htm", "*NS", "Wacholder", "", "", "", "", "", "", "", "Früchte", "Früchte", "", "", "", "", "", ""],
["w/waldmeister.htm", "", "Waldmeister", "", "", "", "Kraut", "Kraut", "Kraut", "", "", "", "", "", "", "", "", ""],
["w/wegmalve.htm", "", "Weg - Malve", "", "", "", "", "", "", "Blüte Blatt", "", "", "", "", "", "", "", ""],
["w/wegwarte.htm", "", "Wegwarte", "", "", "", "", "", "", "Kraut", "Kraut", "Kraut Wurzel", "Kraut Wurzel", "Kraut Wurzel", "", "O / nein", "Galle, Leber und Magen, Appetit", "Wegränder, Weiden, Brachland, Steinbrüche."],
["w/weidenroeschen.htm", "", "Weidenröschen, kleinblütiges", "", "", "", "", "", "Kraut", "Kraut", "Kraut", "Kraut", "", "", "", "", "", ""],
["w/weissdorn.htm", "", "Weißdorn", "", "", "", "", "Blüte Blatt", "", "", "Früchte", "Früchte", "Früchte", "", "", "nein", "Herz, Blutdruck", "Lichte Gebüsche, Laub- und Kiefernwälder, Gärten, Hecken"],
["w/wermut.htm", "", "Wermut", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["w/wiesenbaerenklau.htm", "", "Wiesen - Bärenklau", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", "", ""],
["w/wiesenklee.htm", "", "Wiesenklee", "", "", "", "", "Blüte", "Blüte", "", "", "Blüte", "", "", "", "", "", ""],
["w/kuemmel.htm", "", "Wiesenkümmel", "", "", "", "", "", "Früchte", "Früchte", "", "", "", "", "", "", "", ""],
["w/wiesenschaumkraut.htm", "", "Wiesen-Schaumkraut", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", "", "", "", ""],
["w/wildemalve.htm", "", "Wilde Malve", "", "", "", "", "", "Blatt Blüte", "Blatt Blüte", "Blatt", "", "", "", "", "", "", ""],
["y/ysop.htm", "", "Ysop", "", "", "", "", "", "", "Kraut", "Kraut", "", "", "", "", "", "", ""],
["z/zaunwinde.htm", "", "Zaunwinde", "", "", "Wurzel", "Wurzel", "", "Kraut", "Kraut", "Kraut", "Wurzel", "Wurzel", "", "", "XX", "Fieber, Menstruationsbeschwerden, ...", "Auwälder, Ufergebüsch, Hecken und Zäune, Röhricht, überall verbreite, wo der Boden feucht ist, bis 1200 m /1500 m Höhe"],
["z/zwiebel.htm", "", "Zwiebel", "", "", "", "", "", "", "", "Zwiebel", "Zwiebel", "Zwiebel", "", "", "", "", ""]]